---
- name: "FUNDERING: Systeem Packages & Fonts"
  become: yes
  ansible.builtin.package:
    name: [micro, vim, kitty, terminator, eza, bat, fzf, jq, btop, curl, git, stow]
    state: present

- name: "FONTS: JetBrainsMono Nerd Font installeren"
  become: no
  ansible.builtin.shell: |
    mkdir -p ~/.local/share/fonts
    curl -fLo "JB.zip" https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
    unzip -o JB.zip -d ~/.local/share/fonts && fc-cache -f && rm JB.zip
  args:
    creates: ~/.local/share/fonts/JetBrainsMono

- name: "DOTFILES: Jouw GitHub Config Clonen"
  become: no
  ansible.builtin.git:
    repo: 'https://github.com/henrydenhengst/linux-desktop-provisioning.git'
    dest: "~/ansible-config"
    update: yes

- name: "CONFIG: Nord Thema & 11px voor Terminals"
  become: no
  ansible.builtin.copy:
    dest: "{{ item.path }}"
    content: "{{ item.content }}"
  loop:
    - path: "~/.config/kitty/kitty.conf"
      content: "font_family {{ font_name }}\nfont_size {{ font_size }}.0\nbackground #2e3440\nforeground #d8dee9"
    - path: "~/.config/micro/settings.json"
      content: '{"colorscheme": "nord", "fontsize": {{ font_size }}}'

- name: "SHELL: Aliassen injecteren"
  become: no
  ansible.builtin.blockinfile:
    path: "~/.{{ ansible_user_shell | basename }}rc"
    marker: "# {mark} ANSIBLE MANAGED ALIASES"
    block: |
      alias ls='eza --icons'
      alias cat='bat --theme="Nord"'
      alias k='kubectl'
      alias ai='ollama run llama3'
      export EDITOR='micro'
