---
- name: "Installeren van Printer & Scanner Stack (CUPS + SANE)"
  ansible.builtin.apt:
    name:
      - cups               # De motor achter het printen
      - cups-filters       # Nodig voor moderne PDF-printing
      - system-config-printer # De visuele instellingen-tool
      - hplip              # Onmisbaar voor 90% van de HP printers
      - sane-utils         # De motor voor scanners
      - simple-scan        # De simpelste scanner-app voor de klant
      - printer-driver-brlaser # Specifieke snelle driver voor Brother printers
      - avahi-daemon       # Cruciaal: hiermee vindt Linux printers automatisch (AirPrint)
    state: present
    update_cache: yes

- name: "Diensten starten en activeren"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - cups
    - avahi-daemon

- name: "Firewall openzetten voor Netwerk Printers (mDNS)"
  ansible.builtin.command: ufw allow 5353/udp
  when: ansible_facts.services['ufw.service'] is defined and ansible_facts.services['ufw.service'].state == 'running'
  ignore_errors: yes

- name: "Toevoegen van de gebruiker aan de 'lpadmin' groep"
  ansible.builtin.user:
    name: "{{ ansible_env.USER | default('gebruiker') }}"
    groups: lpadmin,scanner
    append: yes
