---
- name: "Office: Installeer Productiviteitstools"
  ansible.builtin.apt:
    name:
      - libreoffice
      - libreoffice-l10n-nl
      - vlc
      - thunderbird
      - firefox-esr
    state: present
