---
- name: Installeer Privacy Tools
  apt:
    name: [ufw, torbrowser-launcher, oniontools, bleachbit, keepassxc, lynis]
    state: present

- name: Configureer Firewall (UFW)
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Hardening - Verwijder telemetry
  apt:
    name: [popularity-contest, reportbug]
    state: absent

- name: Voer Lynis Security Scan uit
  shell: lynis audit system --quick
  register: lynis_result
  ignore_errors: yes

- name: Sla Lynis rapport lokaal op
  copy:
    content: "{{ lynis_result.stdout }}"
    dest: "/var/log/lynis-report-{{ ansible_date_time.date }}.log"
