---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installeer basis systeemtools
  apt:
    name: [curl, wget, git, htop, net-tools, p7zip-full, vim]
    state: present

- name: Automatische Hardware Detectie - Microcode
  apt:
    name: "{{ 'intel-microcode' if ansible_processor[1] is search('Intel') else 'amd64-microcode' }}"
    state: present

- name: Check voor Nvidia GPU
  shell: lspci | grep -i nvidia
  register: nvidia_check
  ignore_errors: yes
  changed_when: false

- name: Installeer Nvidia drivers indien nodig
  apt:
    name: nvidia-driver
    state: present
  when: nvidia_check.rc == 0

- name: Installeer Standaard Kantoor Software
  apt:
    name: [libreoffice, libreoffice-l10n-nl, vlc, firefox-esr, thunderbird]
    state: present

- name: Systeeminstellingen (Tijd & Taal)
  timezone:
    name: Europe/Amsterdam
