---
- name: "Standaard: Configureer Apt-Proxy naar Sluis"
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/01proxy
    content: 'Acquire::http::Proxy "http://192.168.100.1:3142";'

- name: "Standaard: Installeer BTRFS-tools en basispakketten"
  ansible.builtin.apt:
    name:
      - btrfs-progs
      - ufw
      - curl
      - htop
    state: present
    update_cache: yes

- name: "Standaard: Activeer Firewall"
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
