---
- name: Richt de PLD Server in
  hosts: all
  become: yes
  roles:
    - network       # Eerst hardware check en IP-configuratie
    - apt_proxy     # Daarna de caching proxy installeren
    - docker        # Optioneel: Docker voor extra tools
